version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: crm_lite_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: CRM_Lite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: i1112006s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CRM_Lite"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: